"""Import the NCERT manifest generated by the Playwright crawler into SQLite."""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
from pathlib import Path
from typing import Iterable

from pypdf import PdfReader


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATABASE_PATH = PROJECT_ROOT / "database" / "studypilot.db"
MANIFEST_PATH = PROJECT_ROOT / "docs" / "syllabus_sources" / "ncert_manifest.json"


def clean_text(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def normalize_title(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def ensure_schema(conn: sqlite3.Connection) -> None:
    schema_path = PROJECT_ROOT / "database" / "schema.sql"
    conn.executescript(schema_path.read_text(encoding="utf-8"))


def connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def extract_text_from_pdf(pdf_path: Path, max_pages: int = 8) -> str:
    reader = PdfReader(str(pdf_path))
    chunks: list[str] = []
    for page in reader.pages[:max_pages]:
        try:
            chunks.append(page.extract_text() or "")
        except Exception:
            continue
    return clean_text("\n".join(chunks))


def extract_headings(text: str) -> list[str]:
    candidates: list[str] = []
    seen: set[str] = set()
    for line in re.split(r"[\r\n]+", text):
      line = clean_text(line)
      if not line or len(line) > 90 or len(line) < 3:
          continue
      if re.fullmatch(r"\d+(\.\d+)?", line):
          continue
      if re.match(r"^(chapter|contents|prelims|guide for using qr code|download complete book)\b", line, re.I):
          continue
      if not re.search(r"[A-Za-z]", line):
          continue
      title_like = line == line.upper() or re.match(r"^[A-Z][A-Za-z0-9 ,:'\"()/-]+$", line)
      if not title_like:
          continue
      key = line.lower()
      if key in seen:
          continue
      seen.add(key)
      candidates.append(line)
      if len(candidates) >= 30:
          break
    return candidates


def insert_node(conn: sqlite3.Connection, **kwargs) -> int:
    columns = [
        "parent_id", "node_type", "source_provider", "grade", "subject", "board", "book_title",
        "chapter_number", "section_number", "title", "content", "source_url", "pdf_url",
        "local_path", "order_index",
    ]
    values = [kwargs.get(col) for col in columns]
    cur = conn.execute(
        f"""
        INSERT INTO syllabus_nodes ({', '.join(columns)})
        VALUES ({', '.join(['?'] * len(columns))})
        """,
        values,
    )
    return int(cur.lastrowid)


def build_tree(conn: sqlite3.Connection, manifest: dict) -> None:
    conn.execute("DELETE FROM syllabus_nodes WHERE source_provider = 'NCERT'")
    conn.execute("DELETE FROM knowledge_entries WHERE source_type = 'NCERT'")

    root_id = insert_node(
        conn,
        parent_id=None,
        node_type="catalog",
        source_provider="NCERT",
        grade=None,
        subject=None,
        board="CBSE",
        book_title=None,
        chapter_number=None,
        section_number=None,
        title="NCERT Textbook Catalog",
        content=f"Imported from {manifest.get('source', '')}.",
        source_url=manifest.get("source", ""),
        pdf_url="",
        local_path="",
        order_index=0,
    )

    for class_entry in manifest.get("classes", []):
        grade = class_entry.get("grade")
        class_id = insert_node(
            conn,
            parent_id=root_id,
            node_type="grade",
            source_provider="NCERT",
            grade=grade,
            subject=None,
            board="CBSE",
            book_title=None,
            chapter_number=None,
            section_number=None,
            title=f"Grade {grade}",
            content=class_entry.get("label", ""),
            source_url=manifest.get("source", ""),
            pdf_url="",
            local_path="",
            order_index=grade or 0,
        )

        for subject_index, subject_entry in enumerate(class_entry.get("subjects", []), start=1):
            subject_name = subject_entry.get("subject", "")
            subject_id = insert_node(
                conn,
                parent_id=class_id,
                node_type="subject",
                source_provider="NCERT",
                grade=grade,
                subject=subject_name,
                board="CBSE",
                book_title=None,
                chapter_number=None,
                section_number=None,
                title=subject_name,
                content="",
                source_url=manifest.get("source", ""),
                pdf_url="",
                local_path="",
                order_index=subject_index,
            )

            for book_index, book_entry in enumerate(subject_entry.get("books", []), start=1):
                book_title = book_entry.get("title", "")
                book_id = insert_node(
                    conn,
                    parent_id=subject_id,
                    node_type="book",
                    source_provider="NCERT",
                    grade=grade,
                    subject=subject_name,
                    board="CBSE",
                    book_title=book_title,
                    chapter_number=None,
                    section_number=None,
                    title=book_title,
                    content="",
                    source_url=book_entry.get("page_url", ""),
                    pdf_url="",
                    local_path="",
                    order_index=book_index,
                )

                for chapter_index, chapter_entry in enumerate(book_entry.get("chapters", []), start=1):
                    chapter_title = normalize_title(chapter_entry.get("label", f"Chapter {chapter_index}"))
                    chapter_pdf_path = Path(chapter_entry.get("pdf_path", ""))
                    chapter_text = ""
                    section_titles: list[str] = []

                    if chapter_pdf_path.exists():
                        chapter_text = extract_text_from_pdf(chapter_pdf_path, max_pages=10)
                        section_titles = extract_headings(chapter_text)

                    chapter_id = insert_node(
                        conn,
                        parent_id=book_id,
                        node_type="chapter",
                        source_provider="NCERT",
                        grade=grade,
                        subject=subject_name,
                        board="CBSE",
                        book_title=book_title,
                        chapter_number=chapter_index,
                        section_number=None,
                        title=chapter_title,
                        content=chapter_text[:5000],
                        source_url=chapter_entry.get("page_url", ""),
                        pdf_url=chapter_entry.get("pdf_url", ""),
                        local_path=str(chapter_pdf_path) if chapter_pdf_path.exists() else "",
                        order_index=chapter_index,
                    )

                    for section_index, section_title in enumerate(section_titles, start=1):
                        insert_node(
                            conn,
                            parent_id=chapter_id,
                            node_type="section",
                            source_provider="NCERT",
                            grade=grade,
                            subject=subject_name,
                            board="CBSE",
                            book_title=book_title,
                            chapter_number=chapter_index,
                            section_number=section_index,
                            title=section_title,
                            content="",
                            source_url=chapter_entry.get("page_url", ""),
                            pdf_url=chapter_entry.get("pdf_url", ""),
                            local_path=str(chapter_pdf_path) if chapter_pdf_path.exists() else "",
                            order_index=section_index,
                        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Import NCERT syllabus manifest into SQLite.")
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))

    conn = connect()
    try:
      ensure_schema(conn)
      build_tree(conn, manifest)
      conn.commit()
    finally:
      conn.close()

    print(f"Imported NCERT syllabus tree from {args.manifest}")


if __name__ == "__main__":
    main()
